# Generated by Django 3.2.7 on 2021-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211207_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newprice',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
