# Generated by Django 3.2.7 on 2021-12-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20211223_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='picture',
            new_name='image',
        ),
    ]
